version = 0.1
[default.deploy.parameters]
stack_name = "backend-api-lambda-blogging-app"
resolve_s3 = true
s3_prefix = "backend-api-lambda-blogging-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
